[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
http_from_scratch = { path = "vendor/http-from-scratch/lib" }
jsonwebtoken = "9.3.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
